apiVersion: v1
kind: Service
metadata:
  name: nyu-project-service
spec:
  selector:
    app: nyu-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
